var MSG = {
  catInOut:"In/Out",
  catDigital:"Digital",
  catAnalog:"Analog",
  catSerialAll:"Serial",
  catSerial:"Serial Uart0-USB",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Software Serial",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catBTSoftSerial:"BT Software Serial",
  catRemoteIR:"IR Remote Control",
  catMotors:"Motors",
  catMotorMRT:"Motor MRT",
  catStepper:"Stepper",
  catServo:"Servo",
  catStorage:"Storage",
  catLedStrip:"Led Strip",
  catST7735:"TFT ST7735",
  catTM1637:"TM1637 display",
  catRTCDS3231:"RTC DS3231",
  catRTCDS1302:"RTC DS1302",
  catMAX7219_7D:"MAX7219 7digit",
  catMAX7219_LM:"MAX7219 Led Matrix",
  catEEprom:"EEPROM",
  catSimpleSensorsALL:"Simple Sensors",
  catSimpleSensors:"Sensors I",
  catSimpleSensors2: "Sensors II",
  catSimpleSensors3: "Sensors III",
  catOtherSensors:"Other Sensors",
  catOtherActuators:"Other Actuators",
  catRadioTEA5767:"Radio TEA5767",
  catDFPlayerMP3:"DFPlayer MP3",
  catKeypad:"Keypad",
  catds18b20:"DS18B20",
  catADXL345:"ADXL345 Accel",
  catTCS3200:"TCS3200 Color",
  catHMC5883:"HMC5883 Compass",
  catRotaryEncoder:"Rotary Encoder",
  catSimpleActuators:"Simple Actuators",
  catDisplay:"Displays",
  catRFID:"RFID MFRC522",
  catSerialLCD:"Serial LCD",
  catSerialLCD_I2C:"LCD I2C",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"String", 
  catDivers:"Various",
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  saveXMLTooltip:"Save XML",
  loadXMLTooltip:"Load XML",
  copycodeTooltip:"Copy Arduino code into clipboard",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Delete all %1 blocks?",
  trashTooltip: "Discard all blocks.",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catArray:"Array",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Time",
  catGenericTime:"Generic",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
