var MSG = {
  catInOut:"In/Out",
  catDigital:"Digital",
  catAnalog:"Analog",
  catSerialAll:"Serial",
  catSerial:"Serial Uart0-USB",
  catSerial1:"Serial Uart1",
  catSoftSerial:"Software Serial",
  catBTAll:"Bluetooth",
  catBTSerial1:"BT Serial Uart1",
  catWIFISerial1:"WiFi Serial1",
  catBTSoftSerial:"BT Software Serial",
  catWIFISoftSerial:"WiFi Soft Serial",
  catAPDS9960:"APDS9960",
  catRemoteIR:"IR Remote Control",
  catMotors:"Motors",
  catMotorMRT:"Motor MRT",
  catServoRot:"Rotation Servo",
  catStepper:"Other steppers",
  catStepper28BYJ:"Stepper 28BYJ",
  catServo:"Servo",
  catStorage:"Storage",
  catLedStrip:"Led Strip",
  catPixy2:"Pixy2",
  catMuVision:"Mu Vision",
  catST7735:"TFT ST7735",
  catNEXTION:"TFT Nextion",
  catTM1637:"TM1637 display",
  catRTCDS3231:"RTC DS3231",
  catRTCDS1302:"RTC DS1302",
  catCommunication:"Communications",
  catMAX7219_7D:"MAX7219 7digit",
  catMAX7219_LM:"MAX7219 Led Matrix",
  catEEprom:"EEPROM",
  catmicroSD:"Micro SD",
  catSimpleSensorsALL:"Simple Sensors",
  catSimpleSensors:"Sensors I",
  catSimpleSensors2: "Sensors II",
  catSimpleSensors3: "Sensors III",
  catOtherSensors:"Other Sensors",
  catOtherActuators:"Other Actuators",
  catRadioTEA5767:"Radio TEA5767",
  catDFPlayerMP3:"DFPlayer MP3",
  catYK5300MP3:"YK5300 MP3",
  catKeypad:"Keypad",
  catds18b20:"DS18B20",
  catADXL345:"ADXL345 Accel",
  catTCS3200:"TCS3200 Color",
  catTCS34725:"TCS34725 Color",
  catCamera:"Camera VC0706",
  catHMC5883:"HMC5883 Compass",
  catRotaryEncoder:"Rotary Encoder",
  catGPS:"GPS NEO-6",
  catSimpleActuators:"Simple Actuators",
  catDisplay:"Displays",
  catVision:"Artificial Vision",
  catRFID:"RFID MFRC522",
  catSerialLCD:"Serial LCD",
  catSerialLCD_I2C:"LCD I2C",
  catLCD:"LCD",
  catOLED:"OLED",
  catString:"String", 
  catInterruptExt:"External Interrupts",
  catDivers:"Various",
  title: "Code",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Save Arduino code into file",
  saveXMLTooltip:"Save XML project",
  loadXMLTooltip:"Load XML project",
  uploadTooltip:"Upload code.Need python script running",
  copycodeTooltip:"Copy Arduino code into clipboard",
  myBtnTooltip:"Examples of preprogramming modes",
  BuyTooltip:"Link to website for buying the kit",
  BoardTooltip:"Link to website for information of the board",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  discard: "Delete all %1 blocks?",
  trashTooltip: "Discard all blocks",
  
  catLogic: "Logic",
  catWIFI:"WiFi",
  catIOT:"IOT",
  catMQTTWifi:"MQTT",
  catRF:"Radio Frequency",
  catRF24L01:"NRF24L01",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catArray:"Array",
  catLists: "Lists",
  catColour: "Colour",
  catTime:"Time",
  catGenericTime:"Generic",
  catAllVar:"Variables",
  catVariables: "Simple variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  warningBadBlock:"This block is not properly connected to other blocks.",
  warningPleaseFix:"Please fix the warning on this block."
  
};
